### ISSUE TITLE
Outdated version in Pypi.

### ISSUE THREAD

**Issue by nievk** [lnbits/bolt11#1]
I ask you to update the [PyPI](https://pypi.org/project/bolt11/) repository to the latest version of [Bolt11](https://github.com/lnbits/bolt11) to the version that is broken.

Thanks :+1:

**Comment by eillarra** [comment]
The library is not published yet, as is still in a design phase. I am planning to work on this again starting next week. I am aiming at February 2021 :)

**Comment by dsbaars** [comment]
Any news regarding this?

**Comment by SachinMeier** [comment]
FWIW you can still install this and use it easily using `pip install git+https://github.com/lnbits/bolt11.git`. However, there is a bug I found in this library regarding invoice parsing. For that reason, I suggest you use my fork until this PR is merged: https://github.com/lnbits/bolt11/pull/4

**Comment by kanzure** [comment]
Will this be updated on PyPI?

**Comment by eillarra** [comment]
Hi, for different reasons I didn't work on this further. Maybe @SachinMeier wants to take the lead here? I can give him access on pip too (I reserved the name there, just in case).

@SachinMeier if you are interested you will need to contact the LNbits team, I don't have access to the settings in this repo (I cannot merge PRs either).

**Comment by SachinMeier** [comment]
I got in touch with them and received acknowledgement but haven't seen any other action.

**Comment by dni** [comment]
brace yourself! pypi key is recovered! soon there is a release

**Comment by dni** [comment]
version 1.0.0 https://pypi.org/project/bolt11/  is released
