### ISSUE TITLE
Issue decoding invoice

### ISSUE THREAD

**Issue by pythcoiner** [lnbits/bolt11#12]
this snippet:
```python
import bolt11

invoice = 'lnbc1950n1pjtrgxnpp5ye3lhh8ye8ywm85evshn9wyhdsdg9a350tdhm3dyw89mwfht8s9qdqqxqyjw5q9q7sqqqqqqqqqqqqqqqqqqqqqqqqq9qsqsp5z22wjrrm0lgl32e0yes38dzmvjxnajrvanhw3hp4duq4k55wl0gsrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glclludsryzx7vvvqqqqqlgqqqqqeqqjqqq3zq0d9kw8q4fhsgxh595f2l0ass4zaj2pdknzhxzzrlf7g5wgsk3nlgzzeduhnp6mva9jehwcq9y4hrllwt6ffl822q5drdgvxtjspmgfnls'
decoded = bolt11.decode(invoice)
```

give me this output:
```shell
Traceback (most recent call last):
  File "/home/pythcoiner/python/bolt11/main.py", line 4, in <module>
    decoded = bolt11.decode(invoice)
  File "/home/pythcoiner/python/bolt11/venv/lib/python3.10/site-packages/bolt11/decode.py", line 82, in decode
    tags["9"] = Features.from_bitstring(tagdata)  # type: ignore
  File "/home/pythcoiner/python/bolt11/venv/lib/python3.10/site-packages/bolt11/models/features.py", line 76, in from_bitstring
    raise ValueError(f"Feature index ({i}) out of range, word_length: {length}")
ValueError: Feature index (100) out of range, word_length: 150
```

invoice generated by Phoenix wallet
edit: pip install from pypi (pip install bolt11)

**Comment by dni** [comment]
hey, thanks for the issue, it seems like the words length of the feature tag is 150 bit, from the spec here i only see 51 used bits. https://github.com/lightning/bolts/blob/master/09-features.md

i had this issue before,  so i added extra, bits like here.  though i have no clue what they exactly mean.

working on a PR now.

**Comment by pythcoiner** [comment]
> it seems like the words length of the feature tag is 150 bit, from the spec here i only see 51 used

maybe @t-bast have more ideas about the meaning of these extra bits?

**Comment by pythcoiner** [comment]
thanks for the quick fix, will try it soon!

**Comment by t-bast** [comment]
We're using an experimental feature bit in Phoenix invoices to advertise optional support for trampoline payments: https://github.com/ACINQ/lightning-kmp/blob/fa58d6725ecff7a218c829842d738e951e6b5ee4/src/commonMain/kotlin/fr/acinq/lightning/Features.kt#L232

BOLT 11 states that you should simply ignore optional feature bits you don't support.

**Comment by pythcoiner** [comment]
thanks for info
